@echo off

echo Running linting, formatting, and type checking for TypeScript SDK...
echo Running linting with fixes...
call pnpm lint:fix
echo Running formatting with fixes...
call pnpm format:fix
echo Running type checking...
call pnpm tsc --noEmit
echo TypeScript SDK checks completed successfully!
