name: Go Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'go/**'
      - '.github/workflows/go-*.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'go/**'
      - '.github/workflows/go-*.yml'

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.55.2
          working-directory: ./go
          args: --timeout=5m --path-prefix=./go
