name: Go Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'go/**'
      - '.github/workflows/go-*.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'go/**'
      - '.github/workflows/go-*.yml'

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
          working-directory: go
